# Generated by Django 4.1.3 on 2023-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBookCustomerCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Name')),
                ('companyLocation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Location')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('contactNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact No')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='Status')),
            ],
        ),
    ]
